# .github/workflow/flutter_build.yml
name: "Flutter Build Deploy"
on:
  push:
    branches:
      - release
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # *****************************************************
      # * SETUP
      # *****************************************************
      - uses: subosito/flutter-action@v2
        with:
          # バージョンの指定
          flutter-version: "3.16.2"
          channel: 'stable'
          # キャッシュの有効化
          cache: true

      # *****************************************************
      # * Build
      # *****************************************************
      - run: flutter pub get
      - run: flutter build web --release --no-tree-shake-icons
      - run: cd build/web
      - run: sed -e 's@<base href=\"/\">@<base href=\"/one/\">@' index.html > tmp
      - run: mv tmp index.html
      - run: zip -r one.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: one
          path: one.zip
