# .github/workflow/flutter_build.yml
name: "Flutter Build Deploy"
on:
  push:
    branches:
      - release
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # *****************************************************
      # * SETUP
      # *****************************************************
      - uses: subosito/flutter-action@v2
        with:
          # バージョンの指定
          flutter-version: "3.16.2"
          channel: 'stable'
          # キャッシュの有効化
          cache: true

      # *****************************************************
      # * Build
      # *****************************************************
      - name: Run flutter version
        run: flutter --version

      - name: Run flutter pub get
        run: flutter pub get
      - run: flutter build web --release --no-tree-shake-icons
      - name: sed
        working-directory: build/web
        run: 
          sed -e 's@<base href=\"/\">@<base href=\"/one/\">@' index.html > tmp
          mv tmp index.html
          zip -r one.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: one
          path: build/web/one.zip
